"""
配置文件
@auther: llf
"""
data:
  reader: cv2  # pil or cv2
  dataset_name:
  dataset_path:
  augments:
    train:
      common:
        ToPILImage:
        SRColorJitter:
        SRGaussianBlur:
        SRRandomAffine:
        RandomHorizontalFlip:
        RandomVerticalFlip:
        ToTensor:     # 不归一化用: PILToTensor, 同时可不用Normalize.
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        RandomErasing:
      special:
        MixUp:
        CutMix:

    val:
      common:
        ToPILImage:
        ToTensor:     # 不归一化用: PILToTensor, 同时可不用Normalize.
        Normalize:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
      special:

model:
  backbone:
  pretrained:
  pretrained_path:
  num_classes:
  loss_mode:

train:
  num_works:
  batch_size:
  lr:
  weight_decay:
  max_epoch:

experiments:
  exp_name:
  resume:
