"""
配置文件
@auther: llf
"""
data:
  reader: cv2  # pil or cv2
  dataset_name:
  dataset_path:
  augments:
    MixUp: True
    CutMix: True
    RandomColorJitter:
    RandomGaussianBlur:
    RandomAffine:
    RandomHorizontalFlip:
    RandomVerticalFlip:
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model:
  backbone_mode:
  loss_mode:
  num_classes:
  pretrained:
  pretrained_path:

train:
  num_works:
  batch_size:
  lr:
  weight_decay:
  max_epoch:

experiments:
  exp_name:
